### ISSUE TITLE
Error: $scope.treeInstance is undefined

### ISSUE THREAD

**Issue by cyberz** [ezraroi/ngJsTree#36]
I'm using AngularJS 1.4.2 and jQuery 2.1.4

my controller:
```javascript
angular.module('app.controller', [
    'ngJsTree'
]).controller('AppController', function ($scope, $log) {
   //... 
    var selected_nodes = $scope.treeInstance.jstree(true).get_selected();
}
```
my template:
`<div js-tree="treeConfig" ng-model="treeData" tree="treeInstance">`

and got: Error: $scope.treeInstance is undefined

**Comment by cyberz** [comment]
I'm found solution:
1) add id="myTreeId" to template:
`<div id="myTreeId" js-tree="treeConfig" ng-model="treeData" tree="treeInstance">`

2) Access to Instance by id:
```javascript
var selected_nodes = angular.element('#myTreeId').jstree(true).get_selected();
```

**Comment by ezraroi** [comment]
You can't access the tree instance in the controller constructor, only after the ready event of the tree is fired. You should not use angular
.element to access it. Look on the demo code

**Comment by melino** [comment]
Just ran into the same problem, after cut und pasting js-tree from the main view.html into a template.html that I include. After that suddenly I had: `$scope.treeInstance is undefined`
Using cyberz's solution it works fine now.
@ezraroi So what's wrong with it? Or can you particular point out what to do when `$scope.treeInstance` fails?
Thanx a lot!

**Comment by ezraroi** [comment]
@melino you must wait for the ready event of the jsTree before using the api instance. In the controller constructor it will not be available

**Comment by isaacfi** [comment]
I have the solution, the problem is to use treeInstance direct to the $scope as:

`<div id="myTreeId" js-tree="treeConfig" ng-model="treeData" tree="treeInstance">`

You have to initialize an object in the controller, for example:

```
function myCtrl(
        $scope) {
$scope.model = {};
...
}
```
After this, use the model in your template as:
`<div id="myTreeId" js-tree="treeConfig" ng-model="treeData" tree="model.treeInstance">`

And in the controller:

$scope.model.treeInstance, wont be undefined.
