### ISSUE TITLE
Infinite loop when nodesWatcher.onAdded is executed

### ISSUE THREAD

**Issue by magrynow** [ezraroi/ngJsTree#40]
Hi,
in nodesWatcher.onAdded there is a code where while loop is used. This loop causes my application hangs up sometimes because callbacks setting blocked=false are not executed. Unfortunately I'm not able to reproduce it on demand, so I'm trying to find a way to leave this loop in some other way than setting this flag.
Can you please share some details why you've decided to use this while loop and what is usage limitation of this design (possible hints to which conforming should make me safe with it)?

**Comment by ezraroi** [comment]
Hi, I am using it and never hanged for me. I think that the contract of the jstree ensures that the callback will be called if the action was successful, otherwise i am changing it back. 
If I remember right, it was causing problems when concurrent calls were made to onAdded as the sequence is important here and also maybe there were some problems with the jstree itslef.

**Comment by magrynow** [comment]
Thank you for your response and hint. Indeed concurrent calls are causing this problem, so assuring sequential access or verifying if parent node is loaded before adding child nodes can help with this problem if it occures.

**Comment by ezraroi** [comment]
Thanks for sharing

**Comment by Harvinator** [comment]
We had our heads banging up against a brick wall with an infinite loop for a while which ended up being because we used a ngResource to get the node collection.

What happened was jstree was trying to pass the collection to the WebWorker via postMessage, which was then throwing an exception (silently) and wasn't firing the create node completion handler. The exception was because postMessage couldn't clone the $promse property (which is added to the collection by ngResource).

Then a side effect was the ngJsTree was waiting indefinitely for the next node to be created, creating an infinite loop.

You can fix by either deleting the $promise property from the node collection or just build a fresh array.
