### ISSUE TITLE
tree data(model) is not updated with state.selected property when some nodes are checked from tree

### ISSUE THREAD

**Issue by Sam89Jha** [ezraroi/ngJsTree#94]
I created tree with some data then I checked few nodes from tree, now I want my tree data with the information about selected property of checkbox if checked. my tree data model is not being updated. It will always remain same which I have used to load the tree for the very first time. 

Please clarify my issue, it will be really helpful for me.

**Comment by deshant** [comment]
Experiencing same issue. The tree is not updating state.checked property of the nodes once it loads.

**Comment by ezraroi** [comment]
will try to check it and report

**Comment by ezraroi** [comment]
is this relevant? #4

**Comment by deshant** [comment]
Yes looks like asking the tree the state of the nodes is the way to do it, instead binding it to the tree data.
I have implemented same thing, instead of looking for state.checked in the tree data I am now asking the tree instance for the ids of the checked nodes, and its working without any issue. 
Thanks for the help!
